## 1. Numpy 시작하기


### 2. Numpy 모듈 불러오기

In [3]:
import numpy as np

### 왜 numpy를 사용해야 하는가?

**list**

In [4]:
L = range(1000)

%timeit [i**2 for i in L]

178 µs ± 242 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


**numpy.array**

In [7]:
N = np.arange(1000)

In [8]:
%timeit N**2

798 ns ± 3.22 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### Numpy.array

numpy의 container, array

In [10]:
arr = np.array([1,2,3])

arr

array([1, 2, 3])

In [12]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr.shape

(3,)

In [14]:
arr_2d.shape

(3, 3)

### Numpy로 연산하기

#### Vector와 Scalar 사이의 연산

In [15]:
x = np.array([1,2,3])
c = 5.0

In [17]:
print("더하기 : {}".format(x + c))
print("빼기 : {}".format(x - c))
print("곱하기 : {}".format(x * c))
print("나누기 : {}".format(x / c))


더하기 : [6. 7. 8.]
빼기 : [-4. -3. -2.]
곱하기 : [ 5. 10. 15.]
나누기 : [0.2 0.4 0.6]


#### Vector와 Vector 사이의 연산

벡터의 **같은 index끼리**연산이 이루어진다.

In [18]:
y = np.array([1,3,5])
z = np.array([2,9,20])

In [19]:
print("더하기 : {}".format(y + z))
print("빼기 : {}".format(y - z))
print("곱하기 : {}".format(y * z))
print("나누기 : {}".format(y / z))

더하기 : [ 3 12 25]
빼기 : [ -1  -6 -15]
곱하기 : [  2  27 100]
나누기 : [0.5        0.33333333 0.25      ]


### Array indexing

**list**와 유사

In [23]:
W = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(W[0,0])

print(W[2,3])

print(W[1,2])

1
12
7


### Array slicing

__list__와 유사

In [24]:
W = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

W[0:2, 1:3]

array([[2, 3],
       [6, 7]])

In [25]:
W[0:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
W[:,2:4]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

### Array의 Broadcasting

피연산자가 연산에 부적합한 형태일 경우 자동으로 형태를 복사하여 연산에 적합하도록 만들어 연산을 수행한다.

#### 1, M x N, N x 1

In [28]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
x = np.array([0,1,0])

x = x[:,None]
print(a)
print(x)
print(a+x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0]
 [1]
 [0]]
[[1 2 3]
 [5 6 7]
 [7 8 9]]


#### 2. M x N, 1 x N

In [29]:
y = np.array([0,1,-1])

print(a)
print(y)
print(a*y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 0  1 -1]
[[ 0  2 -3]
 [ 0  5 -6]
 [ 0  8 -9]]


#### 3. M x 1, 1 x N

In [31]:
t = np.array([1,2,3])
t = t[:, None]

u = np.array([2,0,-2])

print(t)
print(u)

print(t + u)

[[1]
 [2]
 [3]]
[ 2  0 -2]
[[ 3  1 -1]
 [ 4  2  0]
 [ 5  3  1]]


### 영벡터

- 원소가 모두 **0**인 벡터(행렬)  
- np.zeros(dim)  
- np.zeros((m,n))  

In [32]:
np.zeros(3)

array([0., 0., 0.])

In [33]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### 일행렬

- 원소가 모두 1인 벡터(행렬)  
- np.ones(dim)  
- np.ones((m,n))

In [34]:
np.ones(3)

array([1., 1., 1.])

In [35]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 대각행렬

- 대각 방향의 성분을 제외한 성분들이 0인 행렬  
- np.diag((m,n))

In [36]:
np.diag((2,4))

array([[2, 0],
       [0, 4]])

In [37]:
np.diag((1,3,5))

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

### 항등행렬

- main diagonal = 1 인 diagonal matrix  
- np.eye(n , dtype = )

In [38]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [39]:
np.eye(3,dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### 행렬 곱

- 행렬간의 곱연산
- np.dot()
- mat1.dot(mat2)
- mat1 @ mat2

In [40]:
mat_1 = np.array([[1,4],[2,3]])
mat_2 = np.array([[7,9],[0,6]])

np.dot(mat_1, mat_2)

array([[ 7, 33],
       [14, 36]])

In [41]:
mat_1.dot(mat_2)

array([[ 7, 33],
       [14, 36]])

### trace method

- main diagonal의 합
- arr.trace()

In [42]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr.trace()

15

In [43]:
np.eye(2, dtype = int).trace()

2

### 행렬식

- 행렬을 대표하는 값 중 하나
- 선형 변환 과정을 통한 Vector의 scaling 척도
- np.linalg.dat(arr)

In [44]:
arr_2 = np.array([[2,3],[1,6]])

arr_2

array([[2, 3],
       [1, 6]])

In [45]:
np.linalg.det(arr_2)

9.000000000000002

In [48]:
arr_3 = np.array([[1,4,7],[2,5,8],[3,6,9]])

arr_3

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [49]:
np.linalg.det(arr_3)

0.0

### 역행렬

- 행렬 A 에 대해서 AB = BA = I를 만족하는 행렬 B
- np.linalg.inv()

In [50]:
mat = np.array([[1,4],[2,3]])
mat

array([[1, 4],
       [2, 3]])

In [51]:
mat_inv = np.linalg.inv(mat)

mat_inv

array([[-0.6,  0.8],
       [ 0.4, -0.2]])

In [52]:
mat @ mat_inv

array([[ 1.00000000e+00,  0.00000000e+00],
       [-1.11022302e-16,  1.00000000e+00]])

### 고유값과 고유벡터

- 정방행렬(N x N) A에 대해서 $Ax = \lambda x$을 만족하는 $\lambda$와 x를 각각 고유값과 고유벡터라 한다.
- np.linalg.eig()

In [53]:
mat = np.array([[2,0,-2],[1,1,-2],[0,0,1]])

mat

array([[ 2,  0, -2],
       [ 1,  1, -2],
       [ 0,  0,  1]])

In [54]:
np.linalg.eig(mat)

(array([1., 2., 1.]),
 array([[0.        , 0.70710678, 0.89442719],
        [1.        , 0.70710678, 0.        ],
        [0.        , 0.        , 0.4472136 ]]))

#### Validation

In [55]:
eig_val, eig_vec = np.linalg.eig(mat)

eig_val

array([1., 2., 1.])

In [56]:
eig_vec

array([[0.        , 0.70710678, 0.89442719],
       [1.        , 0.70710678, 0.        ],
       [0.        , 0.        , 0.4472136 ]])

In [57]:
 mat @ eig_vec[:, 0]

array([0., 1., 0.])

In [58]:
eig_val[0] * eig_vec[:,0]

array([0., 1., 0.])

## Exercises  
### 1. L2 norm을 구하는 함수를 작성하라

In [68]:
def get_L2_norm(arr):
    arr = np.array(arr)
    norm = (sum(arr ** 2))**0.5
    return norm

In [69]:
arr = [2,2]

In [70]:
print(get_L2_norm(arr))

2.8284271247461903


### 2. 주어진 행렬이 singular matrix인지 확인하는 함수를 작성하라

In [75]:
def is_singular(mat):
    answer = np.linalg.det(mat)
    
    if answer == 0:
        return True
    else:
        return False
        

In [76]:
a = np.array([[1,2,3,],[4,5,6],[7,8,9]])

b = np.array([[2,3,4],[5,6,7],[8,9,10]])

c = np.array([[1,2,3],[4,5,6],[7,8,10]])

In [77]:
print(is_singular(a))

print(is_singular(b))

print(is_singular(c))

True
True
False
